var exybore = {
    mainTitle: 'Exybore - Projets de dév\'',
    description: 'Immergez-vous dans le fabuleux monde de la programmation',
    home: 'Accueil',
    projects: 'Projets',
    social: 'Social',
    about: 'A propos',
    discover: 'Découvrez les derniers projets',
    discoverDesc: 'Il y a beaucoup de projets sur le site et vous pouvez choisir de contribuer à eux, ou simplement de les télécharger afin de les tester et les utiliser chez vous.',
    openSource: 'Open-Source',
    simple: 'Simple',
    useful: 'Utiles',
    openSourceDesc: 'Tout le monde peut contribuer pour les projets et les faire grandir',
    simpleDesc: 'Tout est documenté donc vous n\'êtes pas perdus',
    usefulDesc: 'Les projets peuvent être combinés avec les votres pour faire un méga projet',
    gotoProjects: 'Aller sur la page des projets',
    news: 'Les dernières nouveautés',
    newsDesc: 'Ici sont les nouveautés les plus importantes en provenances des réseaux sociaux. Si vous voulez avoir plus de contact, allez sur la page des <a href="social">réseaux sociaux</a>.',
    twitter: 'Twitter',
    discord: 'Discord',
    bop: 'BecauseOfProg',
    twitterDesc: 'Mon endroit à nouveautés, où je poste souvent des informations et autres trucs funs. Vous pouvez aussi me tweeter pour toute question !',
    discordDesc: 'Vous voulez un support ou une question rapide ? Rejoignez-donc mon serveur Discord juste en dessous ! Vous pouvez aussi discuter avec la communauté.',
    bopDesc: 'Ceci est mon blog, avec d\'autres membres. Vous pouvez trouver des articles sur l\'informatique et le numérique, ainsi que des tutoriels de programmation.',
    sitemap: 'Sitemap',
    contact: 'Contact',
    translate: 'Vous voulez traduire le site ?',
    translateDesc: '<a href="https://github.com/Exybore/exy-trad-platform">Allez ici</a> ou choisissez la langue sur laquelle vous voulez apporter votre contribution juste en dessous !'
};

