var exybore = {
    mainTitle: 'Exybore - Projets de dév\'',
    description: 'Immergez-vous dans le monde de la programmation',
    home: 'Accueil',
    projects: 'Projets',
    social: 'Social',
    about: 'A propos',
    discover: 'Découvrez les derniers projets',
    discoverDesc: 'There are many projects on this website and you can choose to contribute to them, or simply download them for testing and using at home.',
    openSource: 'Open-Source',
    simple: 'Simple',
    useful: 'Utiles',
    openSourceDesc: 'Tout le monde peut contribuer pour les projets et les faire grandir',
    simpleDesc: 'Tout est documenté donc vous n\'êtes pas perdus',
    usefulDesc: 'Les projets peuvent être combinés avec les votres pour faire un méga projet',
    gotoProjects: 'Aller sur la page des projets',
    news: 'Les dernières nouveautés',
    newsDesc: 'Here is the most important news provided from social networks. If you want more contacts, go to the <a href="social">social networks</a> page.',
    twitter: 'Twitter',
    discord: 'Discord',
    bop: 'BecauseOfProg',
    twitterDesc: 'My news place, where I often post informations or other fun stuff. You can tweet me for any question !',
    discordDesc: 'Want quick support, help or question ? Just join the Discord server right here ! You can also chat with the community',
    bopDesc: 'Ceci est mon blog, avec d\'autres membres. Vous pouvez trouver des articles sur l\'informatique et le numérique, ainsi que des tutoriels de programmation.',
    sitemap: 'Sitemap',
    contact: 'Contact',
    switchToLang: 'Mettre le site en Anglais'
};

