var exybore = {
    mainTitle: 'Exybore - Proyectos de Desarrollo',
    description: 'Sumerge en el fabuloso mundo del desarrollo',
    home: 'Recepción',
    projects: 'Proyectos',
    social: 'Social',
    about: 'A proposito',
    discover: 'Descube los últimos projectos',
    discoverDesc: 'There are many projects on this website and you can choose to contribute to them, or simply download them for testing and using at home.',
    openSource: 'Open-Source',
    simple: 'Sencillo',
    useful: 'Útil',
    openSourceDesc: 'Everyone can contribute for the projects and make them growing up',
    simpleDesc: 'Everything is correctly documented so you aren\'t disappointed',
    usefulDesc: 'Projects can be combinated with yours to make a powerful final project',
    gotoProjects: 'Go to the projects page',
    news: 'Las últimas novedad',
    newsDesc: 'Here is the most important news provided from social networks. If you want more contacts, go to the <a href="social">social networks</a> page.',
    twitter: 'Twitter',
    discord: 'Discord',
    bop: 'BecauseOfProg',
    twitterDesc: 'My news place, where I often post informations or other fun stuff. You can tweet me for any question !',
    discordDesc: 'Want quick support, help or question ? Just join the Discord server right here ! You can also chat with the community',
    bopDesc: 'This is my french blog, with other members. You can found numeric and informatic news, and programming courses.',
    sitemap: 'Plan del sitio',
    contact: 'Contact',
    translate: 'Want to help translating the website ?',
    translateDesc: '<a href="https://github.com/Exybore/exy-trad-platform">Just go here</a> or choose the language you want to contribute for below !'
};
